import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import { Button } from "@chakra-ui/react";
import { useSession, signIn, signOut } from "next-auth/react";
import CardWrapper from "./components/card-wrapper";

export default function Home() {
  const { data: session } = useSession();

  if (session) {
    return (
      <>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
          <CardWrapper title="Welcome Example Github Auth With Next Auth">
            <Button colorScheme="blue" onClick={() => signOut()} size="md">
              Sign Out
            </Button>
          </CardWrapper>
        </main>
      </>
    );
  }
  // cons
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <CardWrapper title="Login Example Github Auth With Next Auth">
          <Button colorScheme="blue" onClick={() => signIn()} size="md">
            Sign in
          </Button>
        </CardWrapper>
      </main>
    </>
  );
}
